### ISSUE TITLE
Downvote notification bug

### ISSUE THREAD

**Issue by Tyler0130** [ReFlar/gamification#22]
When a new discussion is made and another user either replies or "likes" the post (or a mod performs some action on it that results in a post to the discussion such as renaming it), the OP gets a notification that a user has downvoted their post when they have in fact not done so.

I'm using PHP 7.1, Flarum 0.1.0-beta.7 and the extension version is 2.0.2.

**Comment by CDK2020** [comment]
I am unable to reproduce, please provide a step by step way to reproduce this

**Comment by Tyler0130** [comment]
I've disabled the extension for now on the site I was using it on. I'll try playing around with it this weekend to see if I can produce some reproduction steps for you.

**Comment by Ralkage** [comment]
@Tyler0130 were you able to reproduce this once more? I will leave this issue open for another week.

**Comment by Tyler0130** [comment]
@Ralkage I haven't had time to play around with this much, no. I'll close this for now and if I get a chance to play around with it further and I figure out something, I'll reopen it later.
