### ISSUE TITLE
Rewritten function causes individual expansion failure

### ISSUE THREAD

**Issue by Csineneo** [ReFlar/gamification#25]
Such as [flarum-ext-circle-groups](https://github.com/clarkwinkelmann/flarum-ext-circle-groups)

After enabling ```clarkwinkelmann/flarum-ext-circle-groups```, there is a colored circle on the avatar. 

See the screenshot:
![](https://camo.githubusercontent.com/41652bbdb78c77333077dbe417bb241b99b82ebd/68747470733a2f2f692e696d6775722e636f6d2f466c7973594d362e706e67)

But the colored circle is gone when I enable ```ReFlar/gamification```.

**Comment by datitisev** [comment]
This is because `UserCard#view` is completely replaced with our own code.
This can be fixed if instead of replacing the code, we simply add onto it.

https://github.com/ReFlar/gamification/blob/master/js/forum/src/components/AddAttributes.js#L46,L106

**Comment by TinghuiWang** [comment]
As I am using this extension in a website I am working on, I spend some time to rewrite those functions so that it is compatible with other extensions. Hope it helps.
