### ISSUE TITLE
Installation failed / Converting like -> upvotes failed

### ISSUE THREAD

**Issue by ThomasF34** [ReFlar/gamification#26]
I installed the extension with the composer command. 
Seems like the extension is loading but it's not working correctly. 

<img width="443" alt="screen shot 2018-04-10 at 15 44 56" src="https://user-images.githubusercontent.com/32480223/38560676-75204e56-3cd6-11e8-9ed1-329a35dbdca9.png">
<img width="370" alt="screen shot 2018-04-10 at 15 46 28" src="https://user-images.githubusercontent.com/32480223/38560677-754a0eda-3cd6-11e8-82f0-0b5f865e67b7.png">

Texts are shown with the "variable name". 
When I upvote a message, the counter is decremented and the vote goes under "downvotes_label"

This weird behaviour started when I clicked on the button to convert the likes into upvotes/downvotes. 
When I did, I got an error on the whole website ("There's an error loading the entire version of the website"). This error has disappeared when I enabled (and then disabled) the Debug Mode.

Since then, I can't make the extension working correctly. 
Do you know the issue ? Do you know how to fix it ?

**Comment by Ralkage** [comment]
Enabling and Disabling debug mode only solves half the problem.

For the translation issue (variable names as you may say), please try to clear your browser cache as well as your Flarum cache within the root of your installation by typing `php flarum cache:clear`in your SSH client.

**Comment by CDK2020** [comment]
Hi @ThomasF34, have you been able to reproduce the problem? How big is your forum?
