### ISSUE TITLE
Ranks problem

### ISSUE THREAD

**Issue by rossoblu93** [ReFlar/gamification#31]
* [x] By agreeing to these terms, you can simply leave this checkbox checked.

### Description

Me again…
With the new 3.0.1 version, when an user reaches the upvote points necessary to unlock the second and the following ranks, these are not automatically updated, next to the username.
The first rank remains instead.

Also, it is no longer possible to control who up/downvoted a post.

Many thanks!

### Steps to Reproduce

video:  https://www.dropbox.com/s/pj42f3ez3veq8jj/rank.mov?dl=0

**Comment by CDK2020** [comment]
So it looks like it's probably related to the "how many ranks to show option" I'll have to confirm.

Can you explain what you mean that you can't control who up/downvoted a post?

**Comment by rossoblu93** [comment]
Sure.
In the 2.x version, you had the possibility to check who voted a post by clicking on the total votes number (between the thumbs).

**Comment by CDK2020** [comment]
Thanks for that, I will fix it by the end of the day today
