### ISSUE TITLE
Ranking page exposes all user base

### ISSUE THREAD

**Issue by mattmezza** [ReFlar/gamification#38]
Hi, sorry for screwing up the issue template.

The ranking page exposes by default the entire user base. While this can be ok for most of the installations, it might be unwanted for some specific ones.

I will try to create a PR to solve this.

**Comment by Ralkage** [comment]
Thank you @mattmezza, we will review your PR as soon as we can.

**Comment by mattmezza** [comment]
Thanks to you @Ralkage 

It is not that common to have such a warm and rapid welcoming to issues/PR

**Comment by Ralkage** [comment]
@mattmezza expect that a lot at ReFlar haha.

If you have Discord, come join us in ReDevs/ReFlar land :) https://discord.gg/y9AyYvG
