### ISSUE TITLE
Add Rank Label/Badge Information Page

### ISSUE THREAD

**Issue by Ralkage** [ReFlar/gamification#46]
Currently, there is a page that shows how many points a user has and what position they are in the ranking system.

What we could possible add and shouldn't be hard to code is an actual rank page that shows the rank label/badge/color and amount of points needed to get to that rank. This is already done on the Administrative side but this page should be read/view-only.

Ideally, this should be discussed first before addressing #47.

The route for this page should be https://example.com/leaderboard/ranks instead of https://example.com/ranks.

@datitisev @CDK2020 what do you fellas think?

Some examples ofc:

https://crackwatch.com/ranks

Not an ideal representation given that it doesn't go in accordance to this extension but it should be similar in concept.

Should this be a PRO feature or basic addition to this repo?

**Comment by Ralkage** [comment]
Not sure if pro or base feature.

@datitisev thoughts?

**Comment by datitisev** [comment]
@Ralkage This seems pretty simple, so probably base.

**Comment by Ralkage** [comment]
Probably won't be doing this, will look into an alternative in the future.
