### ISSUE TITLE
Error when clicking on notification icon

### ISSUE THREAD

**Issue by datitisev** [ReFlar/gamification#50]
Reported @ https://discuss.flarum.org/d/17851-notification-icon-fails-due-to-gamification-extension

```php
ReflectionException: Class Reflar\Gamification\Listeners\PostBasicSerializer does not exist in 
vendor/illuminate/container/Container.php:752
```

`PostBasicSerializer` is not imported at https://github.com/ReFlar/gamification/blob/master/src/Listeners/EventHandlers.php#L104

**Comment by CDK2020** [comment]
Closed in e788881b14d963f98a19ff3fe81ecd50fbf7b501
