### ISSUE TITLE
Experience and reward system

### ISSUE THREAD

**Issue by Ralkage** [ReFlar/gamification#51]
I've been thinking about this for a week now and I believe that adding a custom experience and reward system would be ideal for this extension because it falls within the whole idea of "Gamification" itself.

Or should these be separate extensions?

Thoughts? Idea's?

**Comment by CDK2020** [comment]
Let's add this in Gam pro, rather than in the base.

**Comment by Ralkage** [comment]
This will either be in Gam Pro or it's own official extension TBH.

Closing until further notice.
